server:
  port: 6001
eureka:
  instance:
    hostname: localhost    #eureka服务端的实例名称
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 客户端(服务提供者)注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/